name: Image

on:
  workflow_dispatch:

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v4
      - name: Build linux amd64 image
        run: docker buildx build --platform linux/amd64 --metadata-file image-metadata.json --tag ghcr.io/example/gcah:${{ github.sha }} .
      - name: Record digest
        run: cat image-metadata.json | tee image-digest.txt
      - uses: actions/upload-artifact@v5
        with:
          name: digest
          path: image-digest.txt
